# Generated by Django 4.2 on 2023-05-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.FloatField()),
                ('ht', models.FloatField()),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
